// utils/excelExportHelper.js
export const generateExcelReport = (data) => {
  // This is a simplified version. In production, you'd want to use a library like xlsx
  // For now, we'll create a CSV that can be opened in Excel
  
  const formatCurrency = (value) => {
    const num = parseFloat(value) || 0;
    return num.toFixed(2);
  };

  const formatDate = (date) => {
    if (!date) return 'N/A';
    try {
      return new Date(date).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
      });
    } catch {
      return 'Invalid Date';
    }
  };

  // Create CSV content
  let csv = '';

  // Add header information
  csv += `Store Name,${data.storeInfo.name}\n`;
  csv += `Address,${data.storeInfo.address}\n`;
  csv += `Phone,${data.storeInfo.phone}\n`;
  csv += `Email,${data.storeInfo.email}\n`;
  csv += `GST,${data.storeInfo.gst}\n`;
  csv += `Report Period,${data.dateRange}\n`;
  csv += `Generated On,${formatDate(data.generatedAt)}\n`;
  csv += `Report Type,${data.reportType.toUpperCase()}\n`;
  csv += `Generated By,${data.user.name}\n\n`;

  // Add summary section
  csv += 'SUMMARY\n';
  csv += `Total Reports,${data.totals.totalReports}\n`;
  csv += `Total Sales,${formatCurrency(data.totals.totalSales)}\n`;
  csv += `Total Purchases,${formatCurrency(data.totals.totalPurchases)}\n`;
  csv += `Total Profit,${formatCurrency(data.totals.totalProfit)}\n`;
  csv += `Total Items,${data.totals.totalItems}\n`;
  csv += `Average Order Value,${formatCurrency(data.totals.averageOrderValue)}\n\n`;

  // Add reports table headers
  csv += 'REPORTS DETAILS\n';
  csv += 'ID,Name,Type,Amount,Status,Date\n';

  // Add reports data
  data.reports.forEach(report => {
    csv += `${report.id || 'N/A'},`;
    csv += `"${report.name || 'N/A'}",`;
    csv += `${report.type || 'N/A'},`;
    csv += `${formatCurrency(report.amount || 0)},`;
    csv += `${report.status || 'N/A'},`;
    csv += `${formatDate(report.date)}\n`;
  });

  // Add footer
  csv += '\n';
  csv += 'This is a computer generated report\n';
  csv += `Generated by Your Store Management System\n`;
  csv += `© ${new Date().getFullYear()} All rights reserved\n`;

  // Convert to base64
  return Buffer.from(csv).toString('base64');
};