// utils/wordExportHelper.js
export const generateWordReport = (data) => {
  const formatCurrency = (value) => {
    const num = parseFloat(value) || 0;
    return num.toFixed(2);
  };

  const formatDate = (date) => {
    if (!date) return 'N/A';
    try {
      return new Date(date).toLocaleDateString('en-US', {
        year: 'numeric',
        month: 'short',
        day: 'numeric',
        hour: '2-digit',
        minute: '2-digit',
      });
    } catch {
      return 'Invalid Date';
    }
  };

  // Create HTML content that Word can open
  const html = `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>Reports ${data.dateRange}</title>
      <style>
        body {
          font-family: 'Calibri', 'Arial', sans-serif;
          margin: 2cm;
          color: #333;
          line-height: 1.5;
        }
        .header {
          text-align: center;
          margin-bottom: 30px;
          padding-bottom: 20px;
          border-bottom: 2px solid #2563eb;
        }
        .store-name {
          font-size: 28px;
          font-weight: bold;
          color: #1e40af;
          margin-bottom: 5px;
        }
        .report-title {
          font-size: 24px;
          font-weight: bold;
          margin: 20px 0;
          color: #2563eb;
        }
        .info-grid {
          display: flex;
          justify-content: space-between;
          margin-bottom: 30px;
          padding: 15px;
          background-color: #f8fafc;
          border: 1px solid #e2e8f0;
        }
        .summary-cards {
          display: flex;
          flex-wrap: wrap;
          gap: 15px;
          margin-bottom: 30px;
        }
        .summary-card {
          flex: 1;
          min-width: 200px;
          padding: 20px;
          background: linear-gradient(135deg, #3b82f6, #2563eb);
          color: white;
          border-radius: 8px;
        }
        .summary-card-title {
          font-size: 14px;
          opacity: 0.9;
          margin-bottom: 5px;
        }
        .summary-card-value {
          font-size: 24px;
          font-weight: bold;
        }
        table {
          width: 100%;
          border-collapse: collapse;
          margin-bottom: 30px;
        }
        th {
          background-color: #f1f5f9;
          font-weight: 600;
          padding: 12px 8px;
          border: 1px solid #e2e8f0;
          color: #475569;
        }
        td {
          padding: 10px 8px;
          border: 1px solid #e2e8f0;
        }
        tr:nth-child(even) {
          background-color: #f8fafc;
        }
        .text-right {
          text-align: right;
        }
        .text-center {
          text-align: center;
        }
        .footer {
          text-align: center;
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e2e8f0;
          font-size: 11px;
          color: #94a3b8;
        }
        .badge {
          padding: 4px 8px;
          border-radius: 4px;
          font-weight: 500;
          display: inline-block;
        }
      </style>
    </head>
    <body>
      <div class="header">
        <div class="store-name">${data.storeInfo.name}</div>
        <div>${data.storeInfo.address}</div>
        <div>${data.storeInfo.phone} | ${data.storeInfo.email}</div>
        <div>GST: ${data.storeInfo.gst}</div>
      </div>

      <div class="report-title">REPORTS SUMMARY</div>
      
      <div class="info-grid">
        <div>
          <strong>Report Period:</strong> ${data.dateRange}<br>
          <strong>Generated On:</strong> ${formatDate(data.generatedAt)}<br>
          <strong>Report Type:</strong> ${data.reportType.toUpperCase()}<br>
          <strong>Generated By:</strong> ${data.user.name}
        </div>
      </div>

      <div class="summary-cards">
        <div class="summary-card">
          <div class="summary-card-title">Total Reports</div>
          <div class="summary-card-value">${data.totals.totalReports}</div>
        </div>
        <div class="summary-card">
          <div class="summary-card-title">Total Sales</div>
          <div class="summary-card-value">$${formatCurrency(data.totals.totalSales)}</div>
        </div>
        <div class="summary-card">
          <div class="summary-card-title">Total Purchases</div>
          <div class="summary-card-value">$${formatCurrency(data.totals.totalPurchases)}</div>
        </div>
        <div class="summary-card">
          <div class="summary-card-title">Total Profit</div>
          <div class="summary-card-value">$${formatCurrency(data.totals.totalProfit)}</div>
        </div>
      </div>

      <table>
        <thead>
          <tr>
            <th>#</th>
            <th>ID</th>
            <th>Name</th>
            <th>Type</th>
            <th class="text-right">Amount ($)</th>
            <th>Status</th>
            <th>Date</th>
          </tr>
        </thead>
        <tbody>
          ${data.reports.map((report, index) => `
            <tr>
              <td class="text-center">${index + 1}</td>
              <td>${report.id || 'N/A'}</td>
              <td>${report.name || 'N/A'}</td>
              <td>
                <span class="badge" style="
                  background-color: ${
                    report.type === 'sales' ? '#10b98120' :
                    report.type === 'purchases' ? '#f59e0b20' :
                    report.type === 'inventory' ? '#8b5cf620' :
                    '#3b82f620'
                  };
                  color: ${
                    report.type === 'sales' ? '#059669' :
                    report.type === 'purchases' ? '#d97706' :
                    report.type === 'inventory' ? '#6d28d9' :
                    '#2563eb'
                  };
                ">
                  ${(report.type || 'N/A').toUpperCase()}
                </span>
              </td>
              <td class="text-right">$${formatCurrency(report.amount || 0)}</td>
              <td class="text-center">
                <span style="
                  color: ${report.status === 'completed' ? '#059669' : '#d97706'};
                  font-weight: 600;
                ">
                  ${(report.status || 'N/A').toUpperCase()}
                </span>
              </td>
              <td>${formatDate(report.date)}</td>
            </tr>
          `).join('')}
        </tbody>
      </table>

      <div class="footer">
        <div>This is a computer generated report for ${data.dateRange}</div>
        <div>Generated by Your Store Management System</div>
        <div>© ${new Date().getFullYear()} All rights reserved</div>
      </div>
    </body>
    </html>
  `;

  // Convert to base64
  return Buffer.from(html).toString('base64');
};